eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
server:
  port: 8766
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enable: true